name: flutter_background_geolocation
description: The most sophisticated background location tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
version: 1.6.1
homepage: https://github.com/transistorsoft/flutter_background_geolocation

dependencies:
  flutter:
    sdk: flutter
  background_fetch: ^0.4.0


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FLTBackgroundGeolocationPlugin

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

